name: Site Deploy

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout
      uses: actions/setup-node@v1
    - name: npm install, build, test and deploy
      run: |
        npm install
        npm run build --if-present
        npm run deploy
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
